if (!nzchar(Sys.getenv("QUARTO_PROJECT_RENDER_ALL"))) {
  quit()
}

fs::file_copy("../README.md", "index.md", overwrite = TRUE)

new_content <- readLines("index.md", warn = FALSE)
new_content <- gsub(
  "align=\"center\"",
  "style=\"text-align: center !important\"",
  new_content
)
new_content <- new_content[-grep("<h1>jarl</h1>", new_content)]

new_content <- c(
  "<!-- ============ -->",
  "<!-- THIS FILE IS AUTOMATICALLY GENERATED. -->",
  "<!-- MODIFY THE README INSTEAD. -->",
  "<!-- ============ -->",
  "",
  "---",
  "toc: false",
  "title: Jarl",
  "---",
  "",
  new_content
)
writeLines(new_content, con = "index.md")
